=== jendcruz22/S2-JS/JLab6-JennyDcruz/examples.zip (contains people.xml, for in-class example)/examples/people2.dtd
<!-- ELEMENT_DEFINITION ELEMENT_NAME (CONTENT) -->
<!ELEMENT people (person*)>
<!ELEMENT person (name, bio?)> <!-- contents with a sequence (using commas), the order in which the element appears must be followed -->

<!-- Attribute data types for DTDs are:
- CDATA (character data)
- ID (unique value following XML naming rules, so ID wouldn't work for id attribute in this case because it's a number)
- IDREF (a reference to an ID)
- ENTITY (you would probably not use this one)
- NMTOKEN (string tokens, where multiple values are separated with spaces) -->

<!-- ATTRIBUTES CAN BE #REQUIRED OR #IMPLIED -->
<!ATTLIST person 
  id CDATA #REQUIRED
  salutation (Mr | Miss | Mrs | Lord | Lady | Sir) "Mr"
  job CDATA #IMPLIED
>

<!ELEMENT name (first, middle?, last)>
<!ELEMENT first (#PCDATA)>
<!ELEMENT middle (#PCDATA)>
<!ELEMENT last (#PCDATA)>

<!ELEMENT bio (#PCDATA | em | strong)*>
<!ELEMENT em (#PCDATA  | strong)*>
<!ELEMENT strong (#PCDATA  | em)*>

=== jendcruz22/S2-JS/JLab6-JennyDcruz/examples.zip (contains people.xml, for in-class example)/examples/people.xml
<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE people SYSTEM "people2.dtd">
<people>
  <person id="1" salutation="Mr" job="accountant">
    <name>
      <first>John</first>
      <last>Doe</last>
    </name>
    <bio>This is an example of text containing <em>other elements</em>.</bio>
  </person>
  <person id="2" salutation="Mr" job="wizard">
    <name>
      <first>Harry</first>
      <last>Potter</last>
    </name>
  </person>
  <person id="3" salutation="Miss" job="engineer">
    <name>
      <first>Jane</first>
      <last>Smith</last>
    </name>
  </person>
</people>
